### ISSUE TITLE
How does this work under the hood?

### ISSUE THREAD

**Issue by uwla** [Canop/codesort#10]
Hello, nice project!

How does this work under the hood? Are you implementing your own analyzer to sort the code or are you using another tool such as TreeSitter?

Since currently there are support for 3 languages, I guess you are not currently using tools such as treeSitter which could parse the syntax for you for several language. This could help improve the project.

Anyways, thanks for project, can't wait to see it for more languages. I am watching out for upcoming releases

**Comment by Canop** [comment]
This is explained here: https://dystroy.org/blog/sort-code/

**Comment by Canop** [comment]
> There is already support for JS, so for TS should be easy to add.

What I suggest is that you test it. And if it doesn't work well, you create an issue with several test cases so that I can fix the parser or create a dedicated one if necessary (and add the test cases as test units)
