### ISSUE TITLE
Incorrect output when using commas in trait bounds

### ISSUE THREAD

**Issue by regexident** [Canop/codesort#4]
Command:

```terminal
codesort --range "6:26"
```

Before:

```rust
trait Foo {}

struct Bar<T>(T);
struct Baz<T>(T);
struct Blee<T>(T);

impl<T> Foo for Blee<T>
where
    T: Copy,
{
    // ...
}

impl<T> Foo for Baz<T>
where
    T: Copy,
{
    // ...
}

impl<T> Foo for Bar<T>
where
    T: Copy,
{
    // ...
}

fn main() {}
```

After:
```rust
trait Foo {}

struct Bar<T>(T);
struct Baz<T>(T);
struct Blee<T>(T);

impl<T> Foo for Bar<T>
where
    T: Copy,

impl<T> Foo for Baz<T>
where
    T: Copy,

impl<T> Foo for Blee<T>
where
    T: Copy,
{
    // ...
}
{
    // ...
}
{
    // ...
}

fn main() {}
```

Remove the comma (`,`) after `T: Copy,` and  stuff works as expected:

```rust
trait Foo {}

struct Bar<T>(T);
struct Baz<T>(T);
struct Blee<T>(T);

impl<T> Foo for Bar<T>
where
    T: Copy
{
    // ...
}

impl<T> Foo for Baz<T>
where
    T: Copy
{
    // ...
}

impl<T> Foo for Blee<T>
where
    T: Copy
{
    // ...
}

fn main() {}
```

**Comment by Canop** [comment]
Thanks.

Please don't propose a PR for that: I'm rewriting the implementation at the moment (I hope to push in a few days).

**Comment by regexident** [comment]
This makes me wonder if using a CST (e.g. via [tree-sitter](https://crates.io/crates/tree-sitter) or [rowan](https://crates.io/crates/rowan)) might be a more robust (and more easily extensible/maintainable) approach over the current DIY scanner one. 🤔

**Comment by regexident** [comment]
I was talking to a friend just a couple of weeks back about how I really really wanted a tool for semantically sorting code blocks (and how I already have too many projects going on right now to write it myself), so I'm super excited about this tool! Thank you!

**Comment by Canop** [comment]
The CST question is one I'm asking myself since the beginning (like... last week, when I realized I needed a tool to sort my match arms).

I'll finish the implementation I'm working on, which is much cleaner than the current one, then think again about all this.

**Comment by Canop** [comment]
(btw, the new implementation solves this case)

**Comment by Canop** [comment]
Here's the new analyzer: https://github.com/Canop/codesort/pull/6

When I started codesort, I just wanted to sort some simple enums and match arms. I thought the problem was simple and it was simple enough for this scope: just identify what lines should stick together.

Then it looked like it worked for more complex lists and this became the new scope. And honestly, why not also sort `impl` blocks, functions, etc. ?

The original line-based approach had to be amended. Analyzer 0.2 is still mostly line based. We'll see if that's robust enough. In the meantime this is a fun adventure :)

**Comment by regexident** [comment]
> Here's the new analyzer: #6

Awesome, will check it out!

> I thought the problem was simple […]

😂

> […] why not also sort impl blocks […]?

I was _very_ surprised to see those working! 🤩

It saved me at least an hour's work yesterday (40+ impls of the same trait), let alone my sanity. 🙏
