### ISSUE TITLE
Behaviour on files

### ISSUE THREAD

**Issue by Eshanatnight** [Canop/codesort#9]
Hi, firstly I love the tool. I was trying to use this in my project. And I saw this "weird" behaviour
If the File starts with a multiline comment of License and the mod statements. they get moved to the bottom

```rust
/*
......
*/

mod a;
mod b;

#[actix_web::main]
fn main() {
//....
}
```

get formatted to 

```rust
#[actix_web::main]
fn main() {
//....
}

/*
......
*/

mod a;
mod b;
```

Is this the intended behaviour?

**Comment by Canop** [comment]
There was no intention for such behaviour.

I never really tried to sort whole files: there's nothing protecting opening comments, nor imports, etc.

A specific function should be specified then designed for that, if we want to  sort whole files.

In the meantime, I suggest to sort on ranges, or internal parts of enums/structs/match, etc.

**Comment by Canop** [comment]
The intended use cases were either:

* choose a line _in_ a list, for example a variant in an `enum`, then sort *around* this line, which sorts all list items (eg variants)
* select the whole range of lines to sort, for example a few `impl` blocks, sort "range.
